// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkWgf_-sNqfJuo07msZiHfoCJDilmR0lI',
    appId: '1:534134330553:web:88e5f027d6409019173768',
    messagingSenderId: '534134330553',
    projectId: 'teamupturf-6ac3d',
    authDomain: 'teamupturf-6ac3d.firebaseapp.com',
    storageBucket: 'teamupturf-6ac3d.firebasestorage.app',
    measurementId: 'G-75T2E7CMND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1jDwQEJWMsZuh-M6ilDyRt-2TaNkCgRQ',
    appId: '1:534134330553:android:e842d1830d044002173768',
    messagingSenderId: '534134330553',
    projectId: 'teamupturf-6ac3d',
    storageBucket: 'teamupturf-6ac3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnNwCyebi2_2AlGjE8o2YHoC8cdXD9Bpg',
    appId: '1:534134330553:ios:c3f63243b7cd9722173768',
    messagingSenderId: '534134330553',
    projectId: 'teamupturf-6ac3d',
    storageBucket: 'teamupturf-6ac3d.firebasestorage.app',
    iosBundleId: 'com.example.teamupTurf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnNwCyebi2_2AlGjE8o2YHoC8cdXD9Bpg',
    appId: '1:534134330553:ios:c3f63243b7cd9722173768',
    messagingSenderId: '534134330553',
    projectId: 'teamupturf-6ac3d',
    storageBucket: 'teamupturf-6ac3d.firebasestorage.app',
    iosBundleId: 'com.example.teamupTurf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkWgf_-sNqfJuo07msZiHfoCJDilmR0lI',
    appId: '1:534134330553:web:cbf3695ad6b42563173768',
    messagingSenderId: '534134330553',
    projectId: 'teamupturf-6ac3d',
    authDomain: 'teamupturf-6ac3d.firebaseapp.com',
    storageBucket: 'teamupturf-6ac3d.firebasestorage.app',
    measurementId: 'G-7DRYRFJW3Z',
  );
}
